version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./wp-data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: myuser
      WORDPRESS_DB_PASSWORD: mypassword
      WORDPRESS_DB_NAME: mydatabase
      WORDPRESS_DEBUG: 1
    networks:
      - wordpress_network

volumes:
  db_data:

networks:
  wordpress_network: